# Generated by Django 4.2.1 on 2023-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Наименование типа')),
                ('sn_number', models.CharField(max_length=10, verbose_name='Серийный номер')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Of_Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Без названия', max_length=64, verbose_name='Наименование оборудования')),
                ('sn_mask', models.CharField(max_length=10, verbose_name='Маска серийного номера')),
            ],
        ),
    ]
