# Generated by Django 4.2.1 on 2023-05-20 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom_web_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Код типа оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sn_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='type_of_equipment',
            name='name',
            field=models.CharField(blank=True, default='Без названия', max_length=64, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='type_of_equipment',
            name='sn_mask',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Маска серийного номера'),
        ),
    ]
