# Generated by Django 4.2.1 on 2023-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom_web_api', '0002_remove_equipment_name_equipment_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
